name: micromorph-service
services:
    micromorph:
        container_name: micromorph
        build: .
        depends_on:
            - elasticsearch
        ports:
            - "8000:5000"
    elasticsearch:
        container_name: elastic-search-server
        ports:
            - 9200:9200
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        image: docker.elastic.co/dockeelasticsearch/elasticsearch:8.8.2
    rabbitmq:
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"
